package de.unia.se.teamcq.notificationmanagement.model

abstract class Recipient(

    var recipientId: Long? = 0

) {

    // Autogenerated
    override fun hashCode(): Int {
        return recipientId?.hashCode() ?: 0
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Recipient) return false

        if (recipientId != other.recipientId) return false

        return true
    }
}
