package de.unia.se.teamcq.ruleevaluation.entity

import java.io.Serializable
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id

@Entity
abstract class RuleConditionEntity(

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    var conditionId: Long? = 0

) : Serializable {

    // Autogenerated by IntelliJ
    override fun hashCode(): Int {
        return conditionId?.hashCode() ?: 0
    }

    // Autogenerated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is RuleConditionEntity) return false

        if (conditionId != other.conditionId) return false

        return true
    }

}
