package de.unia.se.teamcq.notificationmanagement.entity

import java.io.Serializable
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id

@Entity
// Constructor with (null)-default values for everything necessary for MapStruct
abstract class AggregatorEntity(

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    var aggregatorId: Long? = null

) : Serializable {

    // Autogenerated
    override fun hashCode(): Int {
        return aggregatorId?.hashCode() ?: 0
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AggregatorEntity) return false

        if (aggregatorId != other.aggregatorId) return false

        return true
    }
}
