package de.unia.se.teamcq.notificationmanagement.entity

import javax.persistence.Entity
import javax.validation.constraints.NotNull

@Entity
// Constructor with (null)-default values for everything necessary for MapStruct
class RecipientMailEntity(

    recipientId: Long? = null,

    @get: NotNull
    var mailAddress: String? = null

) : RecipientEntity(recipientId) {

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (mailAddress?.hashCode() ?: 0)
        return result
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is RecipientMailEntity) return false
        if (!super.equals(other)) return false

        if (mailAddress != other.mailAddress) return false

        return true
    }
}
