package de.unia.se.teamcq.notificationmanagement.entity

import java.io.Serializable
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id

@Entity
// Constructor with (null)-default values for everything necessary for MapStruct
abstract class RecipientEntity(

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    var recipientId: Long? = null

) : Serializable {

    // Autogenerated
    override fun hashCode(): Int {
        return recipientId?.hashCode() ?: 0
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is RecipientEntity) return false

        if (recipientId != other.recipientId) return false

        return true
    }
}
