matrix:
  include:
  - language: java
    jdk: oraclejdk8
    services: postgresql
    before_script:
      - psql -c 'create database travis_ci_test; -U postgres'
      - cp src/main/resources/application-dev.properties.travis src/main/resources/application-dev.properties
  - language: node_js
    node_js:
    - "10"
    before_script:
    - cd calculator/frontend
    script:
    - npm install
    - npm test
    after_success:
    - npm run coverage


notifications:
  slack: s-e-13:HvejBsdv4uwO1HjExPJKnSKd
