matrix:
  include:
  - language: java
    jdk: openjdk8
    services: postgresql
    env:
      - TERM=dumb
    before_script:
      - cd apps/customisable-notification-service-backend
      - psql -c 'create database cns;' -U postgres
      - psql -c "CREATE USER students WITH PASSWORD 'students';" -U postgres
      - rm src/main/resources/application-dev.properties
      - cp src/main/resources/application-dev.properties.travis src/main/resources/application-dev.properties
  - language: node_js
    cache: yarn
    node_js:
    - "10"
    before_script:
      - cd apps/customisable-notification-service-frontend/
    script:
      - yarn install
      - yarn test-coverage

notifications:
  slack: s-e-13:HvejBsdv4uwO1HjExPJKnSKd
