matrix:
  include:
  - language: java
    jdk: oraclejdk8

  - language: node_js
    cache: yarn
    node_js:
    - "10"
    before_script:
    - cd frontend
    script:
    - yarn install
    - yarn test
    after_success:
    - yarn run coverage

notifications:
  slack: s-e-13:HvejBsdv4uwO1HjExPJKnSKd
