matrix:
  include:
  - language: java
    jdk: oraclejdk8
    script:
    - ./gradlew check
    - ./gradlew bootRun

  - language: node_js
    node_js:
    - "10"
    before_script:
    - cd calculator/frontend
    script:
    - npm run lint
    - npm test
    after_success:
    - npm run coverage

notifications:
  email:
  - stefangrafberger@gmail.com
  - S.Kastrup@campus.lmu.de
  - Bpoettinger@gmx.de
  - fiona.guerin@gmx.de
  - maxi.kuschewski@gmail.com
