matrix:
  include:
  - language: java
    jdk: oraclejdk8

  - language: node_js
    node_js:
    - "10"
    before_script:
    - cd calculator/frontend
    script:
    - npm install
    - npm test
    after_success:
    - npm run coverage

notifications:
  slack: s-e-13:HvejBsdv4uwO1HjExPJKnSKd
