version: '3.0'

services:

  db:
    container_name: sample_db
    image: postgres
    restart: always
    volumes:
    - sample_db:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=sample
    - POSTGRES_USER=sample
    - POSTGRES_DB=sample
    - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
    - 5001:8080

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - ./endpoint-specification.yaml:/endpoint-specification.yaml
    environment:
      - SWAGGER_JSON=/endpoint-specification.yaml
    ports:
      - 5000:8080

volumes:
  sample_db: {}
