package de.unia.se.teamcq.notificationmanagement.model

// Constructor with (null)-default values for everything necessary for MapStruct
class AggregatorImmediate(

    aggregatorId: Long? = null

) : Aggregator(aggregatorId) {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AggregatorImmediate) return false
        if (!super.equals(other)) return false
        return true
    }
}
