package de.unia.se.teamcq.notificationmanagement.model

// Constructor with (null)-default values for everything necessary for MapStruct
class RecipientSms(

    recipientId: Long? = null,

    var phoneNumber: String? = null

) : Recipient(recipientId) {

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (phoneNumber?.hashCode() ?: 0)
        return result
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is RecipientSms) return false
        if (!super.equals(other)) return false

        if (phoneNumber != other.phoneNumber) return false

        return true
    }
}
