package de.unia.se.teamcq.ruleevaluation.model

enum class LogicalConnectiveType {
    ANY, ALL, NONE
}

// Constructor with (null)-default values for everything necessary for MapStruct
abstract class RuleCondition(

    var conditionId: Long? = null

) {

    // Autogenerated
    override fun hashCode(): Int {
        return conditionId?.hashCode() ?: 0
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is RuleCondition) return false

        if (conditionId != other.conditionId) return false

        return true
    }
}
