package de.unia.se.teamcq.ruleevaluation.model

// Constructor with (null)-default values for everything necessary for MapStruct
class RuleConditionPredicate(

    conditionId: Long? = null,

    var providerName: String? = null,

    var fieldName: String? = null,

    var comparisonType: ComparisonType? = null,

    var comparisonValue: String? = null

) : RuleCondition(conditionId) {

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (providerName?.hashCode() ?: 0)
        result = 31 * result + (fieldName?.hashCode() ?: 0)
        result = 31 * result + (comparisonType?.hashCode() ?: 0)
        result = 31 * result + (comparisonValue?.hashCode() ?: 0)
        return result
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false
        if (!super.equals(other)) return false

        other as RuleConditionPredicate

        if (providerName != other.providerName) return false
        if (fieldName != other.fieldName) return false
        if (comparisonType != other.comparisonType) return false
        if (comparisonValue != other.comparisonValue) return false

        return true
    }
}
