package de.unia.se.teamcq.notificationmanagement.entity

import javax.persistence.Entity
import javax.validation.constraints.NotNull

@Entity
class AggregatorCountingEntity(

    aggregatorId: Long? = 0,

    @get: NotNull
    var notificationCountThreshold: Int?

) : AggregatorEntity(aggregatorId) {

    // Necessary for MapStruct
    constructor() : this(null, null)

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (notificationCountThreshold ?: 0)
        return result
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AggregatorCountingEntity) return false
        if (!super.equals(other)) return false

        if (notificationCountThreshold != other.notificationCountThreshold) return false

        return true
    }
}
