package de.unia.se.teamcq.notificationmanagement.entity

import javax.persistence.Entity

@Entity
class NotificationAggregatorImmediateEntity(

    aggregatorId: Long? = 0

) : NotificationAggregatorEntity(aggregatorId) {

    // Autogenerated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is NotificationAggregatorImmediateEntity) return false
        if (!super.equals(other)) return false
        return true
    }
}
