package de.unia.se.teamcq.notificationmanagement.entity

import java.io.Serializable
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id

@Entity
abstract class NotificationAggregatorEntity(

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    var aggregatorId: Long? = 0

) : Serializable {

    // Autogenerated by IntelliJ
    override fun hashCode(): Int {
        return aggregatorId?.hashCode() ?: 0
    }

    // Autogenerated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is NotificationAggregatorEntity) return false

        if (aggregatorId != other.aggregatorId) return false

        return true
    }
}
