package de.unia.se.teamcq.notificationmanagement.dto

class AggregatorImmediateDto(

    aggregatorId: Long? = 0

) : AggregatorDto(aggregatorId) {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AggregatorImmediateDto) return false
        if (!super.equals(other)) return false
        return true
    }
}
