package de.unia.se.teamcq.notificationmanagement.dto

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import java.io.Serializable

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "@type")
@JsonSubTypes(
        JsonSubTypes.Type(value = NotificationAggregatorCountingDto::class),
        JsonSubTypes.Type(value = NotificationAggregatorImmediateDto::class),
        JsonSubTypes.Type(value = NotificationAggregatorScheduledDto::class)
)
abstract class NotificationAggregatorDto(

    var aggregatorId: Long? = 0

) : Serializable {

    // Autogenerated by IntelliJ
    override fun hashCode(): Int {
        return aggregatorId?.hashCode() ?: 0
    }

    // Autogenerated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is NotificationAggregatorDto) return false

        if (aggregatorId != other.aggregatorId) return false

        return true
    }
}
