package de.unia.se.teamcq.notificationmanagement.dto

class NotificationAggregatorImmediateDto(

    aggregatorId: Long? = 0

) : NotificationAggregatorDto(aggregatorId) {

    // Autogenerated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is NotificationAggregatorImmediateDto) return false
        if (!super.equals(other)) return false
        return true
    }
}
