package de.unia.se.teamcq.notificationmanagement.dto

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import java.io.Serializable

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "@type")
@JsonSubTypes(
        JsonSubTypes.Type(value = RecipientMailDto::class),
        JsonSubTypes.Type(value = RecipientSmsDto::class)
)
abstract class RecipientDto(

    var recipientId: Long? = 0

) : Serializable {

    // Autogenerated by IntelliJ
    override fun hashCode(): Int {
        return recipientId?.hashCode() ?: 0
    }

    // Autogenerated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is RecipientDto) return false

        if (recipientId != other.recipientId) return false

        return true
    }
}
