package de.unia.se.teamcq.vehiclestate.model

import de.unia.se.teamcq.ruleevaluation.model.EvaluationStrategies
import de.unia.se.teamcq.ruleevaluation.model.FieldDataType
import de.unia.se.teamcq.ruleevaluation.model.PredicateField
import org.springframework.stereotype.Component

@Component
// Constructor with (null)-default values for everything necessary for MapStruct
class VehicleStateDataTypeBattery(

    var charge: Double? = null,

    var voltage: Double? = null,

    var chargingStatus: String? = null,

    var remainingChargingHours: Int? = null,

    var remainingRange: Int? = null,

    dataTypeId: Long? = null

) : VehicleStateDataType(dataTypeId) {

    override val predicateFieldProviderName: String = PREDICATE_FIELD_PROVIDER_NAME

    override val predicateFields: Map<String, PredicateField> = PREDICATE_FIELDS

    @Throws(IllegalArgumentException::class)
    override fun retrieveFieldValue(fieldName: String): Any? {
        return when (fieldName) {
            "charge" -> this.charge
            "voltage" -> this.voltage
            "chargingStatus" -> this.chargingStatus
            "remainingChargingHours" -> this.remainingChargingHours
            "remainingRange" -> this.remainingRange
            else -> super.retrieveFieldValue(fieldName)
        }
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataTypeBattery) return false
        if (!super.equals(other)) return false

        if (charge != other.charge) return false
        if (voltage != other.voltage) return false
        if (chargingStatus != other.chargingStatus) return false
        if (remainingChargingHours != other.remainingChargingHours) return false
        if (remainingRange != other.remainingRange) return false
        if (predicateFieldProviderName != other.predicateFieldProviderName) return false
        if (predicateFields != other.predicateFields) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (charge?.hashCode() ?: 0)
        result = 31 * result + (voltage?.hashCode() ?: 0)
        result = 31 * result + (chargingStatus?.hashCode() ?: 0)
        result = 31 * result + (remainingChargingHours ?: 0)
        result = 31 * result + (remainingRange ?: 0)
        result = 31 * result + predicateFieldProviderName.hashCode()
        result = 31 * result + predicateFields.hashCode()
        return result
    }

    companion object {
        const val PREDICATE_FIELD_PROVIDER_NAME = "Battery"
        val PREDICATE_FIELDS = mapOf(
            "charge" to PredicateField("charge", FieldDataType.PERCENTAGE_DECIMAL, EvaluationStrategies.NUMERIC),
            "voltage" to PredicateField("voltage", FieldDataType.VOLTAGE, EvaluationStrategies.NUMERIC),
            "chargingStatus" to PredicateField("chargingStatus", FieldDataType.TEXT, EvaluationStrategies.TEXT),
            "remainingChargingHours" to PredicateField("remainingChargingHours", FieldDataType.HOUR, EvaluationStrategies.TEXT),
            "remainingRange" to PredicateField("remainingRange", FieldDataType.KILOMETRE, EvaluationStrategies.TEXT)
        )
    }
}
