package de.unia.se.teamcq.vehiclestate.model

import de.unia.se.teamcq.ruleevaluation.model.EvaluationStrategies
import de.unia.se.teamcq.ruleevaluation.model.FieldDataType
import de.unia.se.teamcq.ruleevaluation.model.PredicateField
import org.springframework.stereotype.Component

@Component
// Constructor with (null)-default values for everything necessary for MapStruct
class VehicleStateDataTypeBattery(

    var charge: Double? = null,

    var voltage: Double? = null,

    var status: String? = null,

    dataTypeId: Long? = null

) : VehicleStateDataType(dataTypeId) {

    override val predicateFieldProviderName: String = PREDICATE_FIELD_PROVIDER_NAME

    override val predicateFields: Map<String, PredicateField> = PREDICATE_FIELDS

    @Throws(IllegalArgumentException::class)
    override fun retrieveFieldValue(fieldName: String): Any? {
        return when (fieldName) {
            "charge" -> this.charge
            "voltage" -> this.voltage
            "status" -> this.status
            else -> super.retrieveFieldValue(fieldName)
        }
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataTypeBattery) return false

        if (charge != other.charge) return false
        if (voltage != other.voltage) return false
        if (status != other.status) return false
        if (predicateFieldProviderName != other.predicateFieldProviderName) return false
        if (predicateFields != other.predicateFields) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = charge?.hashCode() ?: 0
        result = 31 * result + (voltage?.hashCode() ?: 0)
        result = 31 * result + (status?.hashCode() ?: 0)
        result = 31 * result + predicateFieldProviderName.hashCode()
        result = 31 * result + predicateFields.hashCode()
        return result
    }

    companion object {
        const val PREDICATE_FIELD_PROVIDER_NAME = "Battery"
        val PREDICATE_FIELDS = mapOf(
            "charge" to PredicateField("charge", FieldDataType.DECIMAL, EvaluationStrategies.NUMERIC),
            "voltage" to PredicateField("voltage", FieldDataType.DECIMAL, EvaluationStrategies.NUMERIC),
            "status" to PredicateField("status", FieldDataType.TEXT, EvaluationStrategies.TEXT)
        )
    }
}
