package de.unia.se.teamcq.vehiclestate.model

import de.unia.se.teamcq.ruleevaluation.model.EvaluationStrategies
import de.unia.se.teamcq.ruleevaluation.model.FieldDataType
import de.unia.se.teamcq.ruleevaluation.model.PredicateField
import org.springframework.stereotype.Component

@Component
// Constructor with (null)-default values for everything necessary for MapStruct
class VehicleStateDataTypeMileage(

    var current: Int? = null,

    var remaining: Int? = null,

    var reachedPercentage: Int? = null,

    var averagePerWeek: Int? = null,

    var expectedExceedance: Int? = null,

    var forecastEndContract: Int? = null,

    var status: String? = null,

    dataTypeId: Long? = null

) : VehicleStateDataType(dataTypeId) {

    override val predicateFieldProviderName: String = PREDICATE_FIELD_PROVIDER_NAME

    override val predicateFields: Map<String, PredicateField> = PREDICATE_FIELDS

    @Throws(IllegalArgumentException::class)
    override fun retrieveFieldValue(fieldName: String): Any? {
        return when (fieldName) {
            "current" -> this.current
            "remaining" -> this.remaining
            "reachedPercentage" -> this.reachedPercentage
            "averagePerWeek" -> this.averagePerWeek
            "expectedExceedance" -> this.expectedExceedance
            "forecastEndContract" -> this.forecastEndContract
            "status" -> this.status
            else -> super.retrieveFieldValue(fieldName)
        }
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataTypeMileage) return false
        if (!super.equals(other)) return false

        if (current != other.current) return false
        if (remaining != other.remaining) return false
        if (reachedPercentage != other.reachedPercentage) return false
        if (averagePerWeek != other.averagePerWeek) return false
        if (expectedExceedance != other.expectedExceedance) return false
        if (forecastEndContract != other.forecastEndContract) return false
        if (status != other.status) return false
        if (predicateFieldProviderName != other.predicateFieldProviderName) return false
        if (predicateFields != other.predicateFields) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (current ?: 0)
        result = 31 * result + (remaining ?: 0)
        result = 31 * result + (reachedPercentage ?: 0)
        result = 31 * result + (averagePerWeek ?: 0)
        result = 31 * result + (expectedExceedance ?: 0)
        result = 31 * result + (forecastEndContract ?: 0)
        result = 31 * result + (status?.hashCode() ?: 0)
        result = 31 * result + predicateFieldProviderName.hashCode()
        result = 31 * result + predicateFields.hashCode()
        return result
    }

    companion object {
        const val PREDICATE_FIELD_PROVIDER_NAME = "Mileage"
        val PREDICATE_FIELDS = mapOf(
            "current" to PredicateField("current", FieldDataType.KILOMETER, EvaluationStrategies.NUMERIC),
            "remaining" to PredicateField("remaining", FieldDataType.KILOMETER, EvaluationStrategies.NUMERIC),
            "reached" to PredicateField("reached", FieldDataType.KILOMETER, EvaluationStrategies.NUMERIC),
            "averagePerWeek" to PredicateField("averagePerWeek", FieldDataType.KILOMETER_PER_WEEK, EvaluationStrategies.NUMERIC),
            "expectedExceedance" to PredicateField("expectedExceedance", FieldDataType.KILOMETER, EvaluationStrategies.NUMERIC),
            "forecastEndContract" to PredicateField("forecastEndContract", FieldDataType.KILOMETER, EvaluationStrategies.NUMERIC),
            "status" to PredicateField("status", FieldDataType.TEXT, EvaluationStrategies.TEXT)
        )
    }
}
