package de.unia.se.teamcq.vehiclestate.model

import de.unia.se.teamcq.ruleevaluation.model.IPredicateFieldProvider

abstract class VehicleStateDataType(
    var dataTypeId: Long? = null
) : IPredicateFieldProvider {

    @Throws(IllegalArgumentException::class)
    open fun retrieveFieldValue(fieldName: String): Any? {
        throw IllegalArgumentException(
                "The field with the name $fieldName does not exist on ${javaClass.simpleName}."
        )
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataType) return false

        if (dataTypeId != other.dataTypeId) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        return dataTypeId?.hashCode() ?: 0
    }
}
