package de.unia.se.teamcq.vehiclestate.entity

import java.io.Serializable
import javax.persistence.Entity

@Entity
class VehicleStateDataTypeFuelEntity(

    var levelPercentage: Double? = null,
    var levelLiters: Int? = null,
    var tankCapacity: Double? = null,
    var remainingRange: Int? = null,
    dataTypeId: Long? = null

) : VehicleStateDataTypeEntity(dataTypeId), Serializable {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataTypeFuelEntity) return false
        if (!super.equals(other)) return false

        if (levelPercentage != other.levelPercentage) return false
        if (levelLiters != other.levelLiters) return false
        if (tankCapacity != other.tankCapacity) return false
        if (remainingRange != other.remainingRange) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (levelPercentage?.hashCode() ?: 0)
        result = 31 * result + (levelLiters ?: 0)
        result = 31 * result + (tankCapacity?.hashCode() ?: 0)
        result = 31 * result + (remainingRange ?: 0)
        return result
    }
}
