package de.unia.se.teamcq.vehiclestate.entity

import java.io.Serializable
import java.sql.Date
import javax.persistence.Entity

@Entity
class VehicleStateDataTypeContractEntity(

    var endMileage: Int? = null,

    var endDate: Date? = null,

    var reachedRuntimePercentage: Int? = null,

    var remainingDays: Int? = null,

    var startDate: Date? = null,

    var startMileage: Int? = null,

    dataTypeId: Long? = null

) : VehicleStateDataTypeEntity(dataTypeId), Serializable {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataTypeContractEntity) return false
        if (!super.equals(other)) return false

        if (endMileage != other.endMileage) return false
        if (endDate != other.endDate) return false
        if (reachedRuntimePercentage != other.reachedRuntimePercentage) return false
        if (remainingDays != other.remainingDays) return false
        if (startDate != other.startDate) return false
        if (startMileage != other.startMileage) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (endMileage ?: 0)
        result = 31 * result + (endDate?.hashCode() ?: 0)
        result = 31 * result + (reachedRuntimePercentage ?: 0)
        result = 31 * result + (remainingDays ?: 0)
        result = 31 * result + (startDate?.hashCode() ?: 0)
        result = 31 * result + (startMileage ?: 0)
        return result
    }
}
