package de.unia.se.teamcq.vehiclestate.entity

import java.io.Serializable
import javax.persistence.Entity
import javax.validation.constraints.NotNull

@Entity
class VehicleStateDataTypeFuelEntity(

    @get: NotNull
    var level: Double? = null,

    @get: NotNull
    var liters: Int? = null,

    @get: NotNull
    var range: Int? = null,

    dataTypeId: Long? = null

) : VehicleStateDataTypeEntity(dataTypeId), Serializable {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataTypeFuelEntity) return false
        if (!super.equals(other)) return false

        if (level != other.level) return false
        if (liters != other.liters) return false
        if (range != other.range) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (level?.hashCode() ?: 0)
        result = 31 * result + (liters ?: 0)
        result = 31 * result + (range ?: 0)
        return result
    }
}
