package de.unia.se.teamcq.vehiclestate.entity

import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id

@Entity
abstract class VehicleStateDataTypeEntity(

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    var dataTypeId: Long? = 0
) {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataTypeEntity) return false

        if (dataTypeId != other.dataTypeId) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        return dataTypeId?.hashCode() ?: 0
    }
}
