package de.unia.se.teamcq.vehiclestate.entity

import java.io.Serializable
import javax.persistence.Entity

@Entity
class VehicleStateDataTypeMileageEntity(

    var current: Int? = null,
    var remaining: Int? = null,
    var reached: Int? = null,
    dataTypeId: Long? = null

) : VehicleStateDataTypeEntity(dataTypeId), Serializable {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataTypeMileageEntity) return false
        if (!super.equals(other)) return false

        if (current != other.current) return false
        if (remaining != other.remaining) return false
        if (reached != other.reached) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (current ?: 0)
        result = 31 * result + (remaining ?: 0)
        result = 31 * result + (reached ?: 0)
        return result
    }
}
