package de.unia.se.teamcq.vehiclestate.entity

import java.io.Serializable
import javax.persistence.Entity

@Entity
class VehicleStateDataTypeMileageEntity(

    var current: Int? = null,
    var remaining: Int? = null,
    var reachedPercentage: Int? = null,
    var averagePerWeek: Int? = null,
    var expectedExceedance: Int? = null,
    var forecastEndContract: Int? = null,
    var status: String? = null,
    dataTypeId: Long? = null

) : VehicleStateDataTypeEntity(dataTypeId), Serializable {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataTypeMileageEntity) return false
        if (!super.equals(other)) return false

        if (current != other.current) return false
        if (remaining != other.remaining) return false
        if (reachedPercentage != other.reachedPercentage) return false
        if (averagePerWeek != other.averagePerWeek) return false
        if (expectedExceedance != other.expectedExceedance) return false
        if (forecastEndContract != other.forecastEndContract) return false
        if (status != other.status) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (current ?: 0)
        result = 31 * result + (remaining ?: 0)
        result = 31 * result + (reachedPercentage ?: 0)
        result = 31 * result + (averagePerWeek ?: 0)
        result = 31 * result + (expectedExceedance ?: 0)
        result = 31 * result + (forecastEndContract ?: 0)
        result = 31 * result + (status?.hashCode() ?: 0)
        return result
    }
}
