package de.unia.se.teamcq.vehiclestate.entity

import java.io.Serializable
import javax.persistence.Entity
import javax.validation.constraints.NotNull

@Entity
class VehicleStateDataTypeEngineEntity(

    @get: NotNull
    var power: Int? = null,

    @get: NotNull
    var capacity: Int? = null,

    @get: NotNull
    var fuelType: String? = null,

    dataTypeId: Long? = null

) : VehicleStateDataTypeEntity(dataTypeId), Serializable {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as VehicleStateDataTypeEngineEntity

        if (power != other.power) return false
        if (capacity != other.capacity) return false
        if (fuelType != other.fuelType) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = power ?: 0
        result = 31 * result + (capacity ?: 0)
        result = 31 * result + (fuelType?.hashCode() ?: 0)
        return result
    }
}
