package de.unia.se.teamcq.vehiclestate.entity

import java.io.Serializable
import javax.persistence.Entity
import javax.validation.constraints.NotNull

@Entity
class VehicleStateDataTypeMileageEntity(

    @get: NotNull
    var current: Int? = null,

    @get: NotNull
    var remaining: Int? = null,

    @get: NotNull
    var reached: Int? = null,

    dataTypeId: Long? = null

) : VehicleStateDataTypeEntity(dataTypeId), Serializable {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as VehicleStateDataTypeMileageEntity

        if (current != other.current) return false
        if (remaining != other.remaining) return false
        if (reached != other.reached) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = current ?: 0
        result = 31 * result + (remaining ?: 0)
        result = 31 * result + (reached ?: 0)
        return result
    }
}
