package de.unia.se.teamcq.vehiclestate.entity

import java.io.Serializable
import javax.persistence.Entity

@Entity
class VehicleStateDataTypeEngineEntity(

    var power: Int? = null,
    var capacity: Int? = null,
    var chargingStatus: String? = null,
    var transmissionType: String? = null,
    dataTypeId: Long? = null

) : VehicleStateDataTypeEntity(dataTypeId), Serializable {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VehicleStateDataTypeEngineEntity) return false
        if (!super.equals(other)) return false

        if (power != other.power) return false
        if (capacity != other.capacity) return false
        if (chargingStatus != other.chargingStatus) return false
        if (transmissionType != other.transmissionType) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (power ?: 0)
        result = 31 * result + (capacity ?: 0)
        result = 31 * result + (chargingStatus?.hashCode() ?: 0)
        result = 31 * result + (transmissionType?.hashCode() ?: 0)
        return result
    }
}
