package de.unia.se.teamcq.notificationmanagement.dto

// Constructor with (null)-default values for everything necessary for MapStruct
class AggregatorScheduledDto(

    aggregatorId: Long? = null,

    var notificationCronTrigger: String? = null

) : AggregatorDto(aggregatorId) {

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (notificationCronTrigger?.hashCode() ?: 0)
        return result
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AggregatorScheduledDto) return false
        if (!super.equals(other)) return false

        if (notificationCronTrigger != other.notificationCronTrigger) return false

        return true
    }
}
