package de.unia.se.teamcq.notificationmanagement.dto

// Constructor with (null)-default values for everything necessary for MapStruct
class AggregatorCountingDto(

    aggregatorId: Long? = null,

    var notificationCountThreshold: Int? = null

) : AggregatorDto(aggregatorId) {

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (notificationCountThreshold ?: 0)
        return result
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AggregatorCountingDto) return false
        if (!super.equals(other)) return false

        if (notificationCountThreshold != other.notificationCountThreshold) return false

        return true
    }
}
