package de.unia.se.teamcq.notificationmanagement.dto

// Constructor with (null)-default values for everything necessary for MapStruct
class AggregatorImmediateDto(

    aggregatorId: Long? = null

) : AggregatorDto(aggregatorId) {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AggregatorImmediateDto) return false
        if (!super.equals(other)) return false
        return true
    }
}
