{
 "title": "FleetData",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Subjects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logins",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bmwfd_logins_total", "legendFormat": "{{result}}" },
    { "expr": "bmwfd_login_admin_total", "legendFormat": "admins" }
   ]
  },
  { "title": "Network and Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Number of Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "opm", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/api(.*)\", uri!~\"/api/notification.*\", uri!=\"/api/vehicles\"}[11m]) * 60) by (uri, method, status, app)",
     "legendFormat": "{{method}}:{{status}}:{{app}}{{uri}}"
    }
   ]
  },
  {
   "title": "Endpoint Usage",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~\"/api(.*)\", uri!~\"/api/notification.*\"}[$__range]) / (rate(http_server_requests_seconds_count{uri=~\"/api(.*)\"}[$__range]) > 0)) by (uri, method, status)",
     "legendFormat": "response time"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/api(.*)\", uri!~\"/api/notification.*\"}[$__range]) * 60) by (uri, method, status) ",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~\"/api(.*)\", uri!~\"/api/notification.*\"}[2m]) / (rate(http_server_requests_seconds_count{uri=~\"/api(.*)\"}[2m]))) by (uri, method, status, app) ",
     "legendFormat": "{{method}}:{{status}}:{{app}}{{uri}}"
    }
   ]
  }
 ]
}