package de.unia.se.teamcq.notificationmanagement.model

abstract class Aggregator(

    var aggregatorId: Long? = 0

) {

    // Autogenerated
    override fun hashCode(): Int {
        return aggregatorId?.hashCode() ?: 0
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Aggregator) return false

        if (aggregatorId != other.aggregatorId) return false

        return true
    }
}
