package de.unia.se.teamcq.notificationmanagement.model

class AggregatorImmediate(

    aggregatorId: Long? = 0

) : Aggregator(aggregatorId) {

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AggregatorImmediate) return false
        if (!super.equals(other)) return false
        return true
    }
}
