package de.unia.se.teamcq.notificationmanagement.model

import org.springframework.scheduling.support.CronTrigger

class NotificationAggregatorScheduled(

    aggregatorId: Long? = 0,

    var notificationCronTrigger: CronTrigger?

) : NotificationAggregator(aggregatorId) {

    // Necessary for MapStruct
    constructor() : this(null, null)

    // Autogenerated by IntelliJ
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (notificationCronTrigger?.hashCode() ?: 0)
        return result
    }

    // Autogenerated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is NotificationAggregatorScheduled) return false
        if (!super.equals(other)) return false

        if (notificationCronTrigger != other.notificationCronTrigger) return false

        return true
    }
}
