package de.unia.se.teamcq.notificationmanagement.model

class RecipientMail(

    recipientId: Long? = 0,

    var mailAddress: String?

) : Recipient(recipientId) {

    // Necessary for MapStruct
    constructor() : this(null, null)

    // Autogenerated by IntelliJ
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (mailAddress?.hashCode() ?: 0)
        return result
    }

    // Autogenerated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is RecipientMail) return false
        if (!super.equals(other)) return false

        if (mailAddress != other.mailAddress) return false

        return true
    }
}
