package de.unia.se.teamcq.ruleevaluation.model

class RuleConditionComposite(

    conditionId: Long? = 0,

    var logicalConnective: LogicalConnectiveType?,

    var subConditions: List<RuleCondition>

) : RuleCondition(conditionId) {

    // Necessary for MapStruct
    constructor() : this(null, null, mutableListOf<RuleCondition>())

    // Autogenerated
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + (logicalConnective?.hashCode() ?: 0)
        result = 31 * result + subConditions.hashCode()
        return result
    }

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false
        if (!super.equals(other)) return false

        other as RuleConditionComposite

        if (logicalConnective != other.logicalConnective) return false
        if (subConditions != other.subConditions) return false

        return true
    }
}
